- name: Get nvme count
  ansible.builtin.shell: ls /dev/* | grep nvme | grep n1 | wc -l
  register: nvme_count

- name: Set nfs thread count
  ansible.builtin.lineinfile:
    path: /etc/nfs.conf
    regexp: '^threads'
    line: '{{ item }}'
  with_items:
    - "[nfsd]"
    - threads=16
  when:
    - ansible_facts['processor_cores']*ansible_facts['processor_count'] > 16

- name: update lvm.conf
  command: bash -c "sudo sed -i 's/system_id_source = \"none\"/system_id_source = \"uname\"/g' /etc/lvm/lvm.conf"
    
- name: disable auto_activation_volume in lvm.conf
  lineinfile:
    path: /etc/lvm/lvm.conf
    insertbefore: '# Configuration option activation/read_only_volume_list'
    line: 'auto_activation_volume_list = []'
    state: present
    create: no

#find_UHP_block_volume
- name: fs_ha and use_uhp is defined
  block:
    - name: Waiting for UHP block plugin to do batch iscsi login to complete
      ansible.builtin.wait_for:
        path: /dev/mapper/mpatha

    - name: Set blk_lst and blk_cnt when fs_ha and use_uhp is defined
      shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | grep "vdc$" | sort
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | grep "vdc$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when: 
    - use_uhp|bool
    - fs_ha|bool

- name: fs_ha is not defined and use_uhp is defined
  block:
    - name: Set blk_lst and blk_cnt when fs_ha is not defined and use_uhp is defined
      shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme |  grep "vdb$" | sort
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme |  grep "vdb$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
    - use_uhp|bool
    - not fs_ha|bool

#find_block_volumes
- name: Waiting for block-attach of Block volumes to complete
  ansible.builtin.wait_for:
    path: /tmp/block-attach.complete

- name: fs_ha is defined and use_uhp is not defined
  block:
    - name: Set blk_lst and blk_cnt when fs_ha is defined and use_uhp is not defined
      shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$"
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd* | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | egrep -v "vdb$" | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
     - fs_ha|bool
     - not use_uhp|bool

- name: fs_ha and use_uhp is not defined
  block:
    - name: Set blk_lst and blk_cnt when fs_ha and use_uhp is not defined
      shell: ls /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | sort
      register: blk_lst

    - shell: ls /dev/oracleoci/oraclevd*  | grep -v vda[0-9] | grep -v vda$ | grep -v nvme | wc -l
      register: blk_cnt

    - name: Process disks
      ansible.builtin.include_tasks: process_disks.yml
  when:
     - not fs_ha|bool
     - not use_uhp|bool
     - nvme_count.stdout|int == 0

- name: Find nvme disks
  block:
    - name: Find nvme disks
      shell: ls /dev/* | grep nvme | grep n1 | sort
      register: nvme_lst

    - shell: ls /dev/* | grep nvme | grep n1 | wc -l
      register: nvme_cnt

    - name: Process disks nvme
      ansible.builtin.include_tasks: process_disks.yml
  when:
     - nvme_count.stdout|int > 0
     - not fs_ha|bool