---
- name: Install nfs client packages
  become: true
  ansible.builtin.yum:
    name:
      - nfs-utils
    state: latest
    lock_timeout: 180

- name: sleep for 60 seconds and continue with play
  wait_for:
    timeout: 60
  delegate_to: localhost