exportfs_client_spec_1_cidr_block: "{{ private_storage_subnet_cidr_block }}"
exportfs_client_spec_2_cidr_block: "{{ public_subnet_cidr_block }}"
exportfs_client_spec_3_cidr_block: "{{ private_fs_subnet_cidr_block }}"
options: '(rw,sync,no_root_squash,no_all_squash,no_subtree_check,insecure_locks)'