{
 "title": "ClusterLabs HA Cluster details",
 "description": "Shows the details of a HA cluster running Pacemaker/Corosync. Brought to you by SUSE.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": "label_values(job)" },
   {
    "name": "dc_instance",
    "query": "query_result(label_replace((ha_cluster_pacemaker_nodes{job='$cluster',status='dc'} == 1), 'ip', '$1', 'instance', '(.*):.*') + on(node, ip) group_left label_replace(label_replace(0 * node_uname_info{job='$cluster'}, 'node', '$1', 'nodename', '(.*)'), 'ip', '$1', 'instance','(.*):.*'))"
   }
  ]
 },
 "panels": [
  {
   "title": "Online nodes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ha_cluster_pacemaker_nodes{instance=\"$dc_instance\", status=\"online\"} == 1) / count(count(ha_cluster_pacemaker_nodes{instance=\"$dc_instance\"}) by (node))"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 7, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(ha_cluster_pacemaker_nodes{status=\"unclean\", instance=\"$dc_instance\"}) by (node)"
    },
    {
     "expr": "sum(ha_cluster_pacemaker_nodes{status=\"online\", instance=\"$dc_instance\"}) by (node)"
    },
    {
     "expr": "sum(ha_cluster_pacemaker_nodes{instance=\"$dc_instance\"}) by (type)"
    }
   ]
  },
  {
   "title": "Active Resources",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ha_cluster_pacemaker_resources{instance=\"$dc_instance\", status=\"active\"} == 1) / count(count(ha_cluster_pacemaker_resources{instance=\"$dc_instance\"}) by (resource,node))"
    }
   ]
  },
  {
   "title": "Quorum votes",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "ha_cluster_corosync_quorum_votes{instance=\"$dc_instance\",type=\"expected_votes\"}",
     "legendFormat": "Expected votes"
    },
    {
     "expr": "ha_cluster_corosync_quorum_votes{instance=\"$dc_instance\",type=\"highest_expected\"}",
     "legendFormat": "Highest expected votes"
    },
    {
     "expr": "ha_cluster_corosync_quorum_votes{instance=\"$dc_instance\", type=\"total_votes\"}",
     "legendFormat": "Total votes"
    },
    {
     "expr": "ha_cluster_corosync_quorum_votes{instance=\"$dc_instance\", type=\"quorum\"}",
     "legendFormat": "Quorum"
    }
   ]
  },
  {
   "title": "Cluster quorate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ha_cluster_corosync_quorate{instance=\"$dc_instance\"}"
    }
   ]
  },
  {
   "title": "Faulty Corosync Rings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ha_cluster_corosync_ring_errors{instance=\"$dc_instance\"}"
    }
   ]
  },
  {
   "title": "Last CIB change",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "ha_cluster_pacemaker_config_last_change{instance=\"$dc_instance\"} * 1000"
    }
   ]
  },
  {
   "title": "Node statuses over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ha_cluster_pacemaker_nodes{instance=\"$dc_instance\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Resource statuses over time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(ha_cluster_pacemaker_resources{instance=\"$dc_instance\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(ha_cluster_pacemaker_resources{instance=\"$dc_instance\"} == 1) by(resource, node, status, role, agent)"
    },
    {
     "expr": "sum(ha_cluster_pacemaker_migration_threshold{instance=\"$dc_instance\"}) by(resource, node)"
    },
    {
     "expr": "sum(ha_cluster_pacemaker_fail_count{instance=\"$dc_instance\"}) by(resource, node)"
    }
   ]
  },
  {
   "title": "Node Attributes",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ha_cluster_pacemaker_node_attributes{instance=\"$dc_instance\"}"
    }
   ]
  },
  {
   "title": "systemd units",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "repeat": "node",
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=~\"((corosync|pacemaker|sbd|prometheus|hawk).*)\", state=\"active\"} + on(instance) group_left(nodename) 0 * node_uname_info{job=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Resource location constraints",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "clamp_min(clamp_max(ha_cluster_pacemaker_location_constraints{instance=\"$dc_instance\"}, 1000000), -1000000)"
    }
   ]
  },
  {
   "title": "SBD Devices",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 28 },
   "targets": [
    {
     "expr": "count(ha_cluster_sbd_devices{instance=\"$dc_instance\"}) by (device,status)"
    },
    {
     "expr": "count(ha_cluster_sbd_devices{instance=\"$dc_instance\",status=\"healthy\"}) by (device,status)"
    }
   ]
  }
 ]
}