- hosts: storage,quorum,monitor
  become: true
  pre_tasks:
   - setup:
      gather_subset:
        - '!all'
        - '!any'
        - 'network'
  tasks:
  - ansible.builtin.include_role:
      name: mon_agent
    when: install_monitor_agent|bool

- hosts: monitor
  become: true
  pre_tasks:
   - setup:
      gather_subset:
        - '!all'
        - '!any'
        - 'network'
  tasks:
  - name: Disable SELinux
    selinux:
      state: disabled
  - name: Stop firewalld
    ansible.builtin.include_role:
      name: firewall
  
- hosts: monitor
  become: true
  vars:
    monitoring: true
  tasks:
    - ansible.builtin.include_role:
        name: prometheus
      when: install_monitor_agent|default(false)|bool
    - ansible.builtin.include_role:
        name: grafana
      when: install_monitor_agent|default(false)|bool