---
- name: Bootstrapping  
  hosts: all 
  become: true
  vars:
    firewall_enabled: true
  roles:
    - bootstrap 
    - packages
    - instance_metadata 

- name: Optional NFS HA performance tuning
  hosts: storage:compute
  become: true
  roles:
    - tuning

- name: Storage Configuration
  hosts: storage
  become: true
  roles: 
    - storage_config
    - nfs_server

- name: Pacemaker Cluster and Resources
  hosts: storage
  become: true
  roles: 
    - pacemaker

- name: Configure NFS Clients
  hosts: compute
  become: true
  roles:
    - nfs_client
